### ISSUE TITLE
Are there responsive helpers? If not, how do people feel about this pattern?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-learn/ember-styleguide#100]
https://gitlab.com/NullVoxPopuli/emberclear/blob/master/packages/frontend/src/ui/styles/utility/flex.scss#L38

In emberclear, I'm using bulma,
so I have some responsive helpers that end up being used like this:

```scss
@mixin flexUtils($modifier) {
  .flex-row#{$modifier} {
    display: flex !important;
    flex-direction: row;
  }

  .flex-column#{$modifier} {
    display: flex !important;
    flex-direction: column;
  }
  // ...
}



@include mobile {
  @include flexUtils('-mobile');
}

@include tablet {
  @include flexUtils('-tablet');
}

@include desktop {
  @include flexUtils('-desktop');
}

@include flexUtils('');
```

this allows me to have more functional-style css, similar to tailwind.

Does something like this already exist?
 - would it be cool if I add some utils to this repo if not?
