### ISSUE TITLE
Add a "video-ratio" helper class

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#244]
As part of https://github.com/ember-learn/ember-website/pull/456#pullrequestreview-309402076 we identified that there was a potential need to add new "ratio helper classes" 

After a long discussion, we decided that it is not necessary to add many general-purpose ratio helper classes but instead we just need one that can be used to ensure that videos retain their 16:9 aspect ratio

**Comment by mansona** [comment]
@pichfl i was going to assign this to you because we discussed it but I guess @ghislaineguerin could also take it 🎉

**Comment by pichfl** [comment]
As we most likely can expect video embeds to be 16:9, we can narrow it down to this:

```html
<div class="embed-video">
    <!-- code from YouTube -->
    <iframe width="640" height="360" src="https://www.youtube.com/embed/rY5D38RQoEg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <!-- /code from YouTube -->
</div>
```

```css
.embed-video {
    position: relative;
    height: 0;
    padding: 0 0 56.25%; /* 16:9 */
}

.embed-video iframe {
    position: absolute;
    top: 0;
    left: 0; 
    right: 0; 
    bottom: 0;
}
```

Typing this up I realize I can just push out a PR for that.
